import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell
import os


def export_notebook(target=None):
    nb = new_notebook(cells=[])

    # ---------------- TITLE ----------------
    nb.cells.append(new_markdown_cell(
        "# Intro to Exploratory Data Analysis (EDA) in Python\n"
        "This notebook was auto-generated by **AI Data Agent**.\n\n"
        "It follows a Kaggle-style EDA workflow:\n"
        "- Dataset overview\n"
        "- Cleaning (duplicates, missing values, dropping columns)\n"
        "- Visual EDA (distributions, correlation heatmap, scatter)\n"
        "- Feature Engineering\n"
        "- Modeling starter code\n"
    ))

    # ---------------- IMPORTS ----------------
    nb.cells.append(new_code_cell(
        "import pandas as pd\n"
        "import numpy as np\n"
        "import matplotlib.pyplot as plt\n"
        "import seaborn as sns\n\n"
        "from agents.cleaning import clean_data\n"
        "from agents.feature_engineering import engineer_features\n"
        "from agents.eda import generate_eda, target_eda\n"
        "from agents.feature_importance import feature_importance\n"
    ))

    # ---------------- LOAD DATA ----------------
    nb.cells.append(new_markdown_cell("## 1. Load Dataset"))
    nb.cells.append(new_code_cell(
        "df_raw = pd.read_csv('your_dataset.csv')\n"
        "df_raw.head()"
    ))

    nb.cells.append(new_markdown_cell("## 2. Dataset Overview"))
    nb.cells.append(new_code_cell(
        "df_raw.shape"
    ))
    nb.cells.append(new_code_cell(
        "df_raw.info()"
    ))
    nb.cells.append(new_code_cell(
        "df_raw.describe(include='all').T"
    ))

    # ---------------- CLEANING ----------------
    nb.cells.append(new_markdown_cell("## 3. Data Cleaning"))
    nb.cells.append(new_code_cell(
        "df_cleaned, cleaning_stats, cleaning_text = clean_data(df_raw)\n"
        "cleaning_text"
    ))
    nb.cells.append(new_code_cell(
        "df_cleaned.head()"
    ))

    # ---------------- EDA ----------------
    nb.cells.append(new_markdown_cell("## 4. Exploratory Data Analysis (EDA)"))
    nb.cells.append(new_code_cell(
        "eda_report = generate_eda(df_cleaned)\n"
        "eda_report"
    ))

    nb.cells.append(new_markdown_cell("### 4.1 Correlation Heatmap"))
    nb.cells.append(new_code_cell(
        "numeric_cols = df_cleaned.select_dtypes(include='number').columns.tolist()\n"
        "if len(numeric_cols) >= 2:\n"
        "    plt.figure(figsize=(7,5))\n"
        "    corr = df_cleaned[numeric_cols].corr()\n"
        "    sns.heatmap(corr, cmap='coolwarm')\n"
        "    plt.title('Correlation Heatmap')\n"
        "    plt.show()"
    ))

    nb.cells.append(new_markdown_cell("### 4.2 Numeric Distributions"))
    nb.cells.append(new_code_cell(
        "for col in numeric_cols[:2]:\n"
        "    plt.figure(figsize=(6,4))\n"
        "    sns.histplot(df_cleaned[col], kde=True)\n"
        "    plt.title(f'Distribution: {col}')\n"
        "    plt.show()"
    ))

    nb.cells.append(new_markdown_cell("### 4.3 Numeric Relationship"))
    nb.cells.append(new_code_cell(
        "if len(numeric_cols) >= 2:\n"
        "    plt.figure(figsize=(6,4))\n"
        "    sns.scatterplot(x=df_cleaned[numeric_cols[0]], y=df_cleaned[numeric_cols[1]])\n"
        "    plt.title(f'{numeric_cols[0]} vs {numeric_cols[1]}')\n"
        "    plt.show()"
    ))

    # ---------------- FEATURE ENGINEERING ----------------
    nb.cells.append(new_markdown_cell("## 5. Feature Engineering"))
    nb.cells.append(new_code_cell(
        "df_features, feature_report = engineer_features(df_cleaned)\n"
        "feature_report"
    ))
    nb.cells.append(new_code_cell("df_features.head()"))

    # ---------------- TARGET LOGIC ----------------
    if target:
        nb.cells.append(new_markdown_cell("## 6. Target-aware EDA"))
        nb.cells.append(new_code_cell(
            f"target_column = '{target}'\n"
            "target_insights = target_eda(df_cleaned, target_column)\n"
            "target_insights"
        ))

        nb.cells.append(new_markdown_cell("## 7. Feature Importance"))
        nb.cells.append(new_code_cell(
            "importance = feature_importance(df_features, target_column)\n"
            "importance[:10]"
        ))

    # Save notebook
    os.makedirs("notebooks", exist_ok=True)
    path = "notebooks/eda_to_modeling.ipynb"
    with open(path, "w", encoding="utf-8") as f:
        nbformat.write(nb, f)

    return path
